name: example
description: Flutter font generator example
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  icon_font_generator:
    path: ../

scripts:
  generate_icons: icon_font_generator
    --from=icons
    --class-name=UiIcons
    --out-font=lib/icon_font/ui_icons.ttf
    --out-flutter=lib/widgets/icons.dart

flutter:
  fonts:
    - family: UiIcons
      fonts:
        - asset: lib/icon_font/ui_icons.ttf
